services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - my_api
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - my_api
    depends_on:
      - db

networks:
  my_api:
    driver: bridge